### PR TITLE
Adds timeouts to metadata

### PR DESCRIPTION
**Pull request by jordanwnolan**
It is helpful to have the timeout data on the metadata. For example, we can the timeouts in middleware.

### CODE REVIEW

**Review by antstorm — CHANGES_REQUESTED** [review]
Thank you, @jordanwnolan! Would it be possible to only include timeouts that are relevant to the task type (i.e. start_to_close is only relevant for activities, while execution for workflows)?

**Comment by jordanwnolan** [comment]
thanks @antstorm . I updated so that only the relevant timeouts are added. It looks like `Decision` doesn't actually have any relevant timeouts?

**Comment by antstorm** [comment]
@jordanwnolan yes, you're right, there are no timeouts on a decision task as `PollForDecisionTaskResponse` suggests. You can still get it via history -> WorkflowExecutionStartedEventAttributes -> taskStartToCloseTimeoutSeconds, but I doubt it's actually useful

**Review by antstorm — APPROVED** [review]
Great, thank you 👍

**Pull request merged**
